# Generated by Django 3.1.2 on 2020-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0004_auto_20200930_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='userRecord',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Undermaintenance', 'Undermaintenance'), ('Retirement', 'Retirement')], default='work', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=200, null=True, verbose_name='Tag Number'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Assest Description'),
        ),
    ]
