# Generated by Django 3.1.2 on 2020-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0005_auto_20201026_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='userRecord',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
