# Generated by Django 3.1.2 on 2020-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0006_auto_20201026_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='userRecord',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
